modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/MoonScenty/CreateRecipeNeedRPM/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-recipe-need-rpm"
logoFile="createrecipeneedrpm.png"
authors="MoonScenty"
description='''
Adds RPM-aware variants of selected Create machines and processing recipe types.
Modpack and datapack authors can define minimum RPM requirements and select
different processing results for the same input based on rotational speed.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0.10,6.1.0)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="createrecipeneedrpm.mixins.json"
    requiredMods=["create"]
